// Generated by bin/updateNodesList
import adder from "./nodes/adder.js";
import async_adder from "./nodes/async_adder.js";
import img_distance from "./nodes/img_distance.js";
import img_edge_detect from "./nodes/img_edge_detect.js";
import img_offset from "./nodes/img_offset.js";
import img_sample from "./nodes/img_sample.js";
import img_threshold from "./nodes/img_threshold.js";
import img_vectorize from "./nodes/img_vectorize.js";
import img_viewer from "./nodes/img_viewer.js";
import number from "./nodes/number.js";
import path_viewer from "./nodes/path_viewer.js";
import worker_example from "./nodes/worker-example.js";
export default {
  adder,
  async_adder,
  img_distance,
  img_edge_detect,
  img_offset,
  img_sample,
  img_threshold,
  img_vectorize,
  img_viewer,
  number,
  path_viewer,
  worker_example
};
