// Generated by bin/updateNodesList
import adder from "./nodes/adder.js";
import async_adder from "./nodes/async_adder.js";
import img_distance from "./nodes/img_distance.js";
import img_threshold from "./nodes/img_threshold.js";
import img_viewer from "./nodes/img_viewer.js";
import number from "./nodes/number.js";
import worker_example from "./nodes/worker-example.js";

export default {
  adder,
  async_adder,
  img_distance,
  img_threshold,
  img_viewer,
  number,
  worker_example
};
